name: Workflow 1

on: workflow_dispatch

jobs:
  workflow-1:
    strategy:
      matrix:
        first-input: [1, 2]
        second-input: [a, b]
    uses: pahalampi/experiment-lab/.github/workflows/template.yml@main
    with:
      input-1: ${{ matrix.first-input }}
      input-2: ${{ matrix.second-input }}
