name: Workflow 1

on: workflow_dispatch

jobs:
  build:
    uses: pahalampi/experiment-lab/.github/workflows/template-build.yml@main
    with:
      input-1: ${{ matrix.first-input }}
      input-2: ${{ matrix.second-input }}
    secrets:
      secret-1: ${{ secrets.FIRST_SECRET }}
